### PR TITLE
Inherit from fishtown analytics

### PR DESCRIPTION
**Pull request by mdelaurentis**
* Change license
* Mention singer.io in the setup.py
* Get rid of requirements.txt

### CODE REVIEW

**Comment by cmcarthur** [comment]
@mdelaurentis can you submit the non-LICENSE changes to the fishtown-analytics repository? tyty

**Comment by mdelaurentis** [comment]
@cmcarthur sure. Do you want to give me commit access, or should I make a PR?

**Comment by cmcarthur** [comment]
just open a PR, i think i can cherry pick out the license commit and merge the rest in

**Comment by mdelaurentis** [comment]
Done, see https://github.com/fishtown-analytics/tap-outbrain/pull/3 @cmcarthur .

**Pull request merged**
